name: Terraform Formatting

on:
  pull_request:
    branches: [main]

jobs:
  terraform-fmt:
    name: terraform-fmt
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run terraform fmt on all subdirectories
      run: |
        for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do
          echo "Checking directory $dir"
          (cd $dir && terraform fmt -check=true) || exit 1
        done

    - name: Report status
      uses: actions/github-script@v0.11
      with:
        script: |
          github.repos.createStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'failure',
            context: 'Terraform fmt check',
            description: 'Terraform fmt check failed'
          });