name: Terraform Formatting

on:
  pull_request:
    branches: [main]

jobs:
  terraform-fmt:
    name: terraform-fmt
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.x

    - name: Format Terraform code
      run: terraform fmt -check=true
      id: format
      env:
        TF_IN_AUTOMATION: 'true'

    - name: Fail pull request if Terraform code is not formatted correctly
      if: ${{ failure() }}
      run: |
        echo "::error::Terraform code is not formatted correctly"
        exit 1
