name: Terraform Formatting

on:
  pull_request:
    branches: [main]

jobs:
  terraform-fmt:
    name: terraform-fmt
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Terraform fmt
      run: |
        for dir in $(find . -type d -name "*tf"); do
          echo "Checking Terraform formatting in ${dir}..."
          terraform fmt -check=true "${dir}"
        done

    - name: Set outcome
      run: |
        if [ $? -ne 0 ]; then
          echo ::error ::There was a Terraform formatting error.
          exit 1
        fi 