name: Terraform Formatting

on:
  pull_request:
    branches: [main]

jobs:
  terraform-fmt:
    name: terraform-fmt
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.x

    - name: Get subdirectories
      run: |
        subdirs=$(find . -type d -not -path '*/\.*')

    - name: Terraform Formatting
      run: |
        for subdir in $subdirs
        do
          cd $subdir
          terraform fmt
          if [ $? -ne 0 ]; then
            echo "Terraform formatting failed in $subdir"
            exit 1
          fi
          cd -
        done

    - name: Report status
      run: |
        if [ $? -ne 0 ]; then
          echo "::error::Terraform formatting failed"
        else
          echo "Terraform formatting complete"
        fi 