name: Terraform Formatting

on:
  pull_request:
    branches: [main]

jobs:
  terraform-fmt:
    name: terraform-fmt
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Terraform fmt
      run: |
        echo "Checking Terraform formatting in modules..."
        terraform fmt -check=true modules

    - name: Set outcome
      run: |
        if [ $? -ne 0 ]; then
          echo ::error ::There was a Terraform formatting error.
          exit 1
        fi 